### ISSUE TITLE
qwak_config.py seems to be missing

### ISSUE THREAD

**Issue by mhaeberli** [barnumbirr/qwak#1]
Installed per instructions; set up a ~/.qwak_config.py file, but importing qwak fails with
```
>>> import qwak
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "qwak/__init__.py", line 17, in <module>
    from qwak_api import (
  File "qwak/qwak_api.py", line 5, in <module>
    from qwak_utils import make_request
  File "qwak/qwak_utils.py", line 11, in <module>
    from qwak_config import config
ImportError: No module named qwak_config
```

**Comment by mhaeberli** [comment]
changed qwak_utils.py in context to:
```
config_file = os.path.expanduser('~/.qwak_config.py')
#sys.path.append(os.path.dirname(os.path.expanduser(config_file)))

#config_file = "/tmp/config.py"
with open(config_file) as f:
    code = compile(f.read(), config_file, 'exec')
    exec(code, globals(), locals())

#from qwak_config import config
```
per http://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path
